feat: github action to install cargo-tarpaulin
kubewarden/github-actions pull request #113
Opened 2024-03-05 15:49 UTC by jvanz

## Description

his action downloads latest stable release of cargo-tarpaulin and installs
that inside of the GitHub action path.

Fix https://github.com/kubewarden/kubewarden-controller/issues/667

2024-03-11 11:51 UTC, viccuad commented
Thanks for tackling this.

Agree with Flavio. Maybe a solution is to use `cargo binstall`, which does the work of checking crates.io, and going to the GH releases to fetch the provided binaries.

They provide a minimal GH action, that we can just copy-paste into our actions, see https://github.com/cargo-bins/cargo-binstall?tab=readme-ov-file#in-github-actions.

2024-03-11 12:53 UTC, flavio commented
We have to download the tarball from the tarpaulin release page and put the `cargo-tarpaulin` binary into the $PATH. We can copy&paste https://github.com/kubewarden/github-actions/tree/main/crane-installer and adapt it.

Once the `cargo-tarpaulin` is into the $PATH, `cargo` will automatically find it when `cargo tarpaulin` is invoked

2024-03-12 07:33 UTC, flavio requested changes

2024-03-12 07:33 UTC, flavio commented on tarpaulin-install/action.yml
> +    default: "0.27.3"
In this case we have the current latest version hard-coded. I would drop this input variable and use the code snippet from below

2024-03-12 07:33 UTC, flavio commented on tarpaulin-install/action.yml
> +
```bash
LATEST_RELEASE=$(curl -s https://api.github.com/repos/xd009642/tarpaulin/releases/latest | jq -r '.tag_name')
```

this currently assigns `0.27.3` to `LATEST_RELEASE`

2024-03-12 15:37 UTC, viccuad approved these changes
LGTM. Maybe worth it to do the bump to 3.1.18 already in this PR, with
`sed --in-place 's/3\.1\.17/3\.1\.18/' $(find . -maxdepth 3 -name "*.yml")`.

2024-03-13 12:12 UTC, merged